services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb-mcp-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: testdb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - mongodb-mcp-network

  mongodb-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongodb-mcp-server
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://admin:password@mongodb:27017/testdb?authSource=admin
      NODE_ENV: development
    depends_on:
      - mongodb
    volumes:
      - ./src:/app/src:ro
      - ./build:/app/build
    networks:
      - mongodb-mcp-network
    stdin_open: true
    tty: true

  # Optional: MongoDB Express for database management
  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongodb-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - mongodb-mcp-network

volumes:
  mongodb_data:

networks:
  mongodb-mcp-network:
    driver: bridge